# Generated by Django 5.2.1 on 2025-10-27 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_supervisor', models.CharField(max_length=20, unique=True, verbose_name='Código de Supervisor')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('experiencia_anos', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('convenios_asignados', models.ManyToManyField(blank=True, related_name='supervisores_asignados', to='convenios.convenio', verbose_name='Convenios Asignados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_general', models.PositiveIntegerField(verbose_name='Calificación General (1-10)')),
                ('puntualidad', models.PositiveIntegerField(verbose_name='Puntualidad (1-10)')),
                ('calidad_informes', models.PositiveIntegerField(verbose_name='Calidad de Informes (1-10)')),
                ('comunicacion', models.PositiveIntegerField(verbose_name='Comunicación (1-10)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.convenio', verbose_name='Convenio')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='supervisores.supervisor', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Evaluación de Supervisor',
                'verbose_name_plural': 'Evaluaciones de Supervisores',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
