# Generated by Django 5.2.1 on 2025-10-27 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_entidad', models.CharField(max_length=200, verbose_name='Empresa/Entidad')),
                ('tipo', models.CharField(choices=[('marco', 'Marco'), ('practicas', 'Prácticas'), ('bienestar', 'Bienestar')], max_length=20, verbose_name='Tipo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido'), ('revision', 'En revisión'), ('juridico', 'En jurídico'), ('firma', 'En firma'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='activo', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo_convenio', models.FileField(blank=True, null=True, upload_to='convenios/', verbose_name='Archivo del Convenio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ActividadConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='convenios.convenio', verbose_name='Convenio')),
            ],
            options={
                'verbose_name': 'Actividad de Convenio',
                'verbose_name_plural': 'Actividades de Convenios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Informe')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo_informe', models.FileField(upload_to='informes/', verbose_name='Archivo del Informe')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='convenios.convenio', verbose_name='Convenio')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
